// <auto-generated />
using System;
using CatrinasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatrinasAPI.Migrations
{
    [DbContext(typeof(CatrinasDbContext))]
    [Migration("20251023170343_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HolaMundoAPI.Models.Acceso", b =>
                {
                    b.Property<int>("Id_Acceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Acceso"));

                    b.Property<string>("Acceso1")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("Acceso");

                    b.HasKey("Id_Acceso");

                    b.HasIndex("Acceso1")
                        .IsUnique();

                    b.ToTable("Accesos");

                    b.HasData(
                        new
                        {
                            Id_Acceso = 1,
                            Acceso1 = "ADM001"
                        },
                        new
                        {
                            Id_Acceso = 2,
                            Acceso1 = "JUE001"
                        },
                        new
                        {
                            Id_Acceso = 3,
                            Acceso1 = "JUE002"
                        },
                        new
                        {
                            Id_Acceso = 4,
                            Acceso1 = "JUE003"
                        });
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Ajuste", b =>
                {
                    b.Property<int>("Id_Ajuste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ajuste"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Publicacion_Resultados")
                        .HasColumnType("bit");

                    b.Property<int>("Tiempo_de_Votacion")
                        .HasColumnType("int");

                    b.HasKey("Id_Ajuste");

                    b.ToTable("Ajustes");

                    b.HasData(
                        new
                        {
                            Id_Ajuste = 1,
                            Activo = true,
                            Fecha = new DateTime(2025, 10, 23, 11, 3, 43, 511, DateTimeKind.Local).AddTicks(2260),
                            Publicacion_Resultados = false,
                            Tiempo_de_Votacion = 30
                        });
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Estado", b =>
                {
                    b.Property<int>("Id_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Estado"));

                    b.Property<string>("Estado1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Estado");

                    b.HasKey("Id_Estado");

                    b.HasIndex("Estado1")
                        .IsUnique();

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id_Estado = 1,
                            Estado1 = "Aguascalientes"
                        },
                        new
                        {
                            Id_Estado = 2,
                            Estado1 = "Baja California"
                        },
                        new
                        {
                            Id_Estado = 3,
                            Estado1 = "Baja California Sur"
                        },
                        new
                        {
                            Id_Estado = 4,
                            Estado1 = "Campeche"
                        },
                        new
                        {
                            Id_Estado = 5,
                            Estado1 = "Chiapas"
                        },
                        new
                        {
                            Id_Estado = 6,
                            Estado1 = "Chihuahua"
                        },
                        new
                        {
                            Id_Estado = 7,
                            Estado1 = "Ciudad de México"
                        },
                        new
                        {
                            Id_Estado = 8,
                            Estado1 = "Coahuila"
                        },
                        new
                        {
                            Id_Estado = 9,
                            Estado1 = "Colima"
                        },
                        new
                        {
                            Id_Estado = 10,
                            Estado1 = "Durango"
                        },
                        new
                        {
                            Id_Estado = 11,
                            Estado1 = "Guanajuato"
                        },
                        new
                        {
                            Id_Estado = 12,
                            Estado1 = "Guerrero"
                        },
                        new
                        {
                            Id_Estado = 13,
                            Estado1 = "Hidalgo"
                        },
                        new
                        {
                            Id_Estado = 14,
                            Estado1 = "Jalisco"
                        },
                        new
                        {
                            Id_Estado = 15,
                            Estado1 = "México"
                        },
                        new
                        {
                            Id_Estado = 16,
                            Estado1 = "Michoacán"
                        },
                        new
                        {
                            Id_Estado = 17,
                            Estado1 = "Morelos"
                        },
                        new
                        {
                            Id_Estado = 18,
                            Estado1 = "Nayarit"
                        },
                        new
                        {
                            Id_Estado = 19,
                            Estado1 = "Nuevo León"
                        },
                        new
                        {
                            Id_Estado = 20,
                            Estado1 = "Oaxaca"
                        },
                        new
                        {
                            Id_Estado = 21,
                            Estado1 = "Puebla"
                        },
                        new
                        {
                            Id_Estado = 22,
                            Estado1 = "Querétaro"
                        },
                        new
                        {
                            Id_Estado = 23,
                            Estado1 = "Quintana Roo"
                        },
                        new
                        {
                            Id_Estado = 24,
                            Estado1 = "San Luis Potosí"
                        },
                        new
                        {
                            Id_Estado = 25,
                            Estado1 = "Sinaloa"
                        },
                        new
                        {
                            Id_Estado = 26,
                            Estado1 = "Sonora"
                        },
                        new
                        {
                            Id_Estado = 27,
                            Estado1 = "Tabasco"
                        },
                        new
                        {
                            Id_Estado = 28,
                            Estado1 = "Tamaulipas"
                        },
                        new
                        {
                            Id_Estado = 29,
                            Estado1 = "Tlaxcala"
                        },
                        new
                        {
                            Id_Estado = 30,
                            Estado1 = "Veracruz"
                        },
                        new
                        {
                            Id_Estado = 31,
                            Estado1 = "Yucatán"
                        },
                        new
                        {
                            Id_Estado = 32,
                            Estado1 = "Zacatecas"
                        });
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Evaluacion", b =>
                {
                    b.Property<int>("Id_Evaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Evaluacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Atuendo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Acceso")
                        .HasColumnType("int");

                    b.Property<int>("Id_Participante")
                        .HasColumnType("int");

                    b.Property<int>("Interaccion")
                        .HasColumnType("int");

                    b.Property<int>("Maquillaje")
                        .HasColumnType("int");

                    b.Property<int>("Pasarela")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Tradiciones")
                        .HasColumnType("int");

                    b.HasKey("Id_Evaluacion");

                    b.HasIndex("Id_Acceso");

                    b.HasIndex("Id_Participante", "Id_Acceso")
                        .IsUnique();

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.HistorialAcceso", b =>
                {
                    b.Property<int>("Id_Historial_Acceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Historial_Acceso"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Acceso")
                        .HasColumnType("int");

                    b.HasKey("Id_Historial_Acceso");

                    b.HasIndex("Id_Acceso");

                    b.ToTable("HistorialAccesos");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Participante", b =>
                {
                    b.Property<int>("Id_Participante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Participante"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Participante");

                    b.HasIndex("Id_Estado");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Id_Acceso")
                        .HasColumnType("int");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Id_Acceso");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Evaluacion", b =>
                {
                    b.HasOne("HolaMundoAPI.Models.Acceso", "Acceso")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("Id_Acceso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HolaMundoAPI.Models.Participante", "Participante")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("Id_Participante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acceso");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.HistorialAcceso", b =>
                {
                    b.HasOne("HolaMundoAPI.Models.Acceso", "Acceso")
                        .WithMany("HistorialAccesos")
                        .HasForeignKey("Id_Acceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acceso");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Participante", b =>
                {
                    b.HasOne("HolaMundoAPI.Models.Estado", "Estado")
                        .WithMany("Participantes")
                        .HasForeignKey("Id_Estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Usuario", b =>
                {
                    b.HasOne("HolaMundoAPI.Models.Acceso", "Acceso")
                        .WithMany()
                        .HasForeignKey("Id_Acceso")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Acceso");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Acceso", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("HistorialAccesos");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Estado", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Participante", b =>
                {
                    b.Navigation("Evaluaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
