// <auto-generated />
using System;
using CatrinasAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CatrinasAPI.Migrations
{
    [DbContext(typeof(CatrinasDbContext))]
    partial class CatrinasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HolaMundoAPI.Models.Acceso", b =>
                {
                    b.Property<int>("Id_Acceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Acceso"));

                    b.Property<string>("Acceso1")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("Acceso");

                    b.HasKey("Id_Acceso");

                    b.HasIndex("Acceso1")
                        .IsUnique();

                    b.ToTable("Accesos");

                    b.HasData(
                        new
                        {
                            Id_Acceso = 1,
                            Acceso1 = "ADM001"
                        },
                        new
                        {
                            Id_Acceso = 2,
                            Acceso1 = "JUE001"
                        },
                        new
                        {
                            Id_Acceso = 3,
                            Acceso1 = "JUE002"
                        },
                        new
                        {
                            Id_Acceso = 4,
                            Acceso1 = "JUE003"
                        });
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Ajuste", b =>
                {
                    b.Property<int>("Id_Ajuste")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ajuste"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Publicacion_Resultados")
                        .HasColumnType("bit");

                    b.Property<int>("Tiempo_de_Votacion")
                        .HasColumnType("int");

                    b.HasKey("Id_Ajuste");

                    b.ToTable("Ajustes");

                    b.HasData(
                        new
                        {
                            Id_Ajuste = 1,
                            Activo = true,
                            Fecha = new DateTime(2025, 10, 23, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Publicacion_Resultados = false,
                            Tiempo_de_Votacion = 30
                        });
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Estado", b =>
                {
                    b.Property<int>("Id_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Estado"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Estado1")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Estado");

                    b.HasKey("Id_Estado");

                    b.HasIndex("Estado1")
                        .IsUnique();

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            Id_Estado = 1,
                            Descripcion = "Participante registrado en el concurso",
                            Estado1 = "Registrado"
                        },
                        new
                        {
                            Id_Estado = 2,
                            Descripcion = "Participante en espera de evaluación",
                            Estado1 = "En Espera"
                        },
                        new
                        {
                            Id_Estado = 3,
                            Descripcion = "Participante siendo evaluado por jueces",
                            Estado1 = "En Votación"
                        },
                        new
                        {
                            Id_Estado = 4,
                            Descripcion = "Participante ya calificado por todos los jueces",
                            Estado1 = "Calificado"
                        },
                        new
                        {
                            Id_Estado = 5,
                            Descripcion = "Participante descalificado del concurso",
                            Estado1 = "Descalificado"
                        },
                        new
                        {
                            Id_Estado = 6,
                            Descripcion = "Participante clasificado como finalista",
                            Estado1 = "Finalista"
                        });
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Evaluacion", b =>
                {
                    b.Property<int>("Id_Evaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Evaluacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Atuendo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaEvaluacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Acceso")
                        .HasColumnType("int");

                    b.Property<int>("Id_Participante")
                        .HasColumnType("int");

                    b.Property<int>("Interaccion")
                        .HasColumnType("int");

                    b.Property<int>("Maquillaje")
                        .HasColumnType("int");

                    b.Property<int>("Pasarela")
                        .HasColumnType("int");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Tradiciones")
                        .HasColumnType("int");

                    b.HasKey("Id_Evaluacion");

                    b.HasIndex("Id_Acceso");

                    b.HasIndex("Id_Participante", "Id_Acceso")
                        .IsUnique();

                    b.ToTable("Evaluaciones");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.HistorialAcceso", b =>
                {
                    b.Property<int>("Id_Historial_Acceso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Historial_Acceso"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Acceso")
                        .HasColumnType("int");

                    b.HasKey("Id_Historial_Acceso");

                    b.HasIndex("Id_Acceso");

                    b.ToTable("HistorialAccesos");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Participante", b =>
                {
                    b.Property<int>("Id_Participante")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Participante"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("Id_Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id_Participante");

                    b.HasIndex("Id_Estado");

                    b.ToTable("Participantes");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Ranking", b =>
                {
                    b.Property<int>("Id_Ranking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Ranking"));

                    b.Property<DateTime>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_Participante")
                        .HasColumnType("int");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Puntos")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_Ranking");

                    b.HasIndex("Id_Participante")
                        .IsUnique();

                    b.ToTable("Rankings");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Usuarios", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreCompleto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("Usuario")
                        .IsUnique();

                    b.ToTable("UsuariosAdmin");

                    b.HasData(
                        new
                        {
                            Id_Usuario = 1,
                            Activo = true,
                            Email = "admin@catrinas.com",
                            FechaCreacion = new DateTime(2025, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NombreCompleto = "Administrador del Sistema",
                            Password = "admin123",
                            Rol = "Administrador",
                            Usuario = "admin"
                        });
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Evaluacion", b =>
                {
                    b.HasOne("HolaMundoAPI.Models.Acceso", "Acceso")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("Id_Acceso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HolaMundoAPI.Models.Participante", "Participante")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("Id_Participante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Acceso");

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.HistorialAcceso", b =>
                {
                    b.HasOne("HolaMundoAPI.Models.Acceso", "Acceso")
                        .WithMany("HistorialAccesos")
                        .HasForeignKey("Id_Acceso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Acceso");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Participante", b =>
                {
                    b.HasOne("HolaMundoAPI.Models.Estado", "Estado")
                        .WithMany("Participantes")
                        .HasForeignKey("Id_Estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Ranking", b =>
                {
                    b.HasOne("HolaMundoAPI.Models.Participante", "Participante")
                        .WithMany("Rankings")
                        .HasForeignKey("Id_Participante")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participante");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Acceso", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("HistorialAccesos");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Estado", b =>
                {
                    b.Navigation("Participantes");
                });

            modelBuilder.Entity("HolaMundoAPI.Models.Participante", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("Rankings");
                });
#pragma warning restore 612, 618
        }
    }
}
